spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: dhome
    password: dhome
    url: jdbc:mysql://172.28.19.88:3306/sell?characterEncoding=utf-8&useSSL=false
    jackson:
      default-property-inclusion: non_null  # 如果字段为null ，统一不返回
server:
  servlet:
    context-path: /sell           # URL的前缀
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  # path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#   com.imooc.sell.LoggerTest: debug
logging:
  level:
    com.imooc.sell.dataObject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
